name: Feature request
about: Suggest an idea or enhancement for this project
title: "[Feature Request] "
labels: enhancement
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to improve our project. Please fill in the details below.
        Before submitting, check our open issues to see if a similar request already exists.

  - type: textarea
    attributes:
      label: Description
      description: Explain your idea in detail. What problem does it solve?
      placeholder: "It would be great if..."

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or related references that might help us understand your request better.
      placeholder: "Additional notes..."

  - type: textarea
    attributes:
      label: suggestion/implementation
      description: Do you have any suggestion how to implement or apply your requested feature? if we find it useful, you will be acknowledged in our Chat AI homepage ;).
      placeholder: "Additional notes..."

  - type: checkboxes
    attributes:
      label: Confirmation
      description: Confirm you've considered the following:
      options:
        - label: I have checked if this feature is already requested
        - label: I have described why this feature would be valuable
